### ISSUE TITLE
Ability to upload your own journals from local

### ISSUE THREAD

**Issue by itssimple** [itssimple/journal-limpet#11]
To ensure that we can store as many journals as possible, we should also let users upload their own journals.

Uploaded journals are not subject to be uploaded to EDDN and EDSM, since they might contain modified data, and we don't want to get banned from sending data :)

**Comment by DlljsCodes** [comment]
Why?

**Comment by itssimple** [comment]
Mostly because there's no good way that I can assure that the uploaded journals could contain a lot of data, that it shouldn't.

Even if I'm not sending the journals anywhere, I would not want Journal Limpet to end up as a file storage for arbitrary files.
