### ISSUE TITLE
Add a FAQ

### ISSUE THREAD

**Issue by itssimple** [itssimple/journal-limpet#17]
We should add a FAQ section somewhere, that will explain certain things about the service.

How much data we can grab from your account, and things like that..

**Comment by Athanasius** [comment]
And I was about to ask about a FAQ on Discord when I saw the message about this issue being opened.

Things like:

Q. How long do you store my journals for?  Any time, or storage, based culling ?

Q. Are the journals you store complete?
A. <no, there's some events missing>

**Comment by itssimple** [comment]
Yeah.. I have to really point out that to my knowledge the journals are "complete", but since I know they aren't, I'll have to add some info about why some data might be missing if you compare your local journals to the ones stored in Journal Limpet.

And it's all because I can't grab data, that isn't in the journal file, stored in the API. ^^
