### ISSUE TITLE
When sending an email for a user to renew their link, Journal Limpet should display a page before the redirect

### ISSUE THREAD

**Issue by Pichu0102** [itssimple/journal-limpet#33]
Currently, clicking the link to login and renew from the journal limpet email, it simply sends you to the Frontier login page. It might be better to first display a page on the Journal Limpet site informing the user to click further to proceed to the Frontier login page, so as to allow for the user to confirm via the URL bar that, indeed, journal limpet's website is the one sending you to login.

**Comment by itssimple** [comment]
Sounds like a really smart idea, I like it!

Will implement it during the weekend.
